config/routes.rb
Sample::Application.routes.draw do

  get "adminclosedtickets/show"

 match "adminclosedtickets/view/:id"  => "adminclosedtickets#view"

  match "adminclosedtickets/assign/:id" => "adminclosedtickets#assign"

match "adminclosedtickets/support/:id" => "adminclosedtickets#support"

  match "contacts/accinfo" => "contacts#accinfo"
  match "home/contactus/:id" => "home#contactus"
  match "contacts/contact" => "contacts#contact"
 match "contacts/contact_update" => "contacts#contact_update"
 match "contacts/acc_update" => "contacts#acc_update"

  devise_for :admins
  devise_for :users
  resources :categories
  resources :news
  resources :depts
  resources :faqs

  resources :tickets do
  resources :posts
  end
  resources :contacts
  match 'home/search' => 'home#search'
  get "admin/createstaff"
  get "home/news"
  get "admin/createstaff"
  get "admin/staffhome"
  get "knowlwedgebase/kbase"
  get "admin/home"
  get "admin/ticket"
  get "home/login"
  get "home/contactus"
  get "opentickets/assignticket"
  get "home/homepage"
  get "adminopentickets/staff"
  get "knowlwedgebase/detail"
  get "staff/ticket"
  get "staff/time"
  get "category/create"
  get "category/update"
  get "category/destroy"
  get "posts/create"
  get "adminopentickets/show"
  get "adminopentickets/assign"
  get "adminopentickets/support"
  get "adminpendingtickets/show"
  match 'tickets/show/:id' => 'tickets#show'
  match 'home/newsview/:id' => 'home#newsview'
  match "knowlwedgebase/show/:id" => "knowlwedgebase#show"
  match "knowlwedgebase/detail/:id" => "knowlwedgebase#detail"
  match "knowlwedgebase/kbase/:id" => "knowlwedgebase#kbase"
  match 'adminpendingtickets/view/:id' => 'adminpendingtickets#view'
  match 'adminpendingtickets/assign/:id' => 'adminpendingtickets#assign'

  match 'adminpendingtickets/change/:id' => 'adminpendingtickets#change'
  match 'adminpendingtickets/support/:id' => 'adminpendingtickets#support'
  match 'adminopentickets/view/:id' => 'adminopentickets#view'
  match 'adminopentickets/assign/:id' => 'adminopentickets#assign'
  match 'adminopentickets/support/:id' => 'adminopentickets#support'
  
   
  
 

    root :to => "home#homepage"
    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
has_many :tickets
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :username, :phone, :mobile, :department, :ticket_notifier, :privilege, :find_your_attachment

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :faqs
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/dept.rb
class Dept < ActiveRecord::Base
	has_many :tickets
end

app/models/faq.rb
class Faq < ActiveRecord::Base
belongs_to :categories	
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :ticket
end

app/models/posts.rb
class Posts < ActiveRecord::Base
belongs_to:tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
has_many :posts
belongs_to :admin
has_one :dept
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
attr_accessible :to, :category, :priority, :subject, :message, :created_at, :updated_at, :status, :customer_name, :user_id, :staff_id, :avatar_file_name, :avatar_file_size, :avatar_file_type, :avatar_file_updatedat,:staff_email, :client_email
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :fullname, :company, :address1, :address2, :city, :state, :country, :phone1, :phone2, :fax, :web, :username, :admin_id
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/createstaff.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>


<DIV id=u59 style="position:absolute; left:299px; top:434px; width:90px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u59_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Username</span></DIV></DIV>
<%= f.text_field :full_name, :id=>"60",:style=>"position:absolute; left:377px; top:349px; width:230px; height:25px; ; ; text-align: left ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none"  %>

<DIV id=u61 style="position:absolute; left:300px; top:350px; width:90px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u61_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Full Name</span></DIV></DIV>
<DIV id=u62 style="position:absolute; left:323px; top:394px; width:50px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u62_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Email</span></DIV></DIV>
<DIV id=u63 style="position:absolute; left:280px; top:584px; width:110px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u63_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Ticket Notifier</span></DIV></DIV>
<%= f.email_field :email, :id=>"64", :style=>"position:absolute; left:377px; top:391px; width:230px; height:25px; ; ; text-align: left ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none"   %>

<%= f.text_field :username, :id=>"65", :style=>"position:absolute; left:378px; top:429px; width:230px; height:25px; ; ; text-align: left ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none"   %>

<DIV id=u66container style="position:absolute; left:378px; top:584px; width:152px; height:16px; ; ; text-align: left " >
<DIV id=u67 style="position:absolute; left:16px; top:0px; width:134px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u67_rtf><span style=" font-family:'Arial'; color:#808080; font-size:10pt;">&nbsp; Receive Email alert</span></DIV></DIV>
</DIV>
<DIV style="position:absolute; left:378px; top:584px; width:152px; height:16px; ; ; text-align: left " ><div id="u66", style="position:absolute; left:-3px; top:-2px;" ><%= f.check_box :ticket_notifier %></div></DIV>
<DIV id=ou68 style="position:absolute; left:230px; top:631px; width:567px; height:180px;; overflow:visible">

<span style="position:absolute; left:-3px; top:-3px; width:575px; height:188px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='Admin -- My Account_files/u68.png',sizingMethod='scale');
"><img style="width:575px; height:188px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="Admin -- My Account_files/u68.png" border="0" alt=""></span>

</DIV>
<DIV id=u68container style="position:absolute; left:230px; top:631px; width:567px; height:180px;; overflow:visible">

<DIV id=u69 style="position:absolute; left:2px; top:81.5px; width:562px; height:16px; ; ; text-align: center ; font-family:Arial; text-align:left;" >
<DIV id=u69_rtf>&nbsp;</DIV></DIV>
</DIV>
<IMG id=u68 src="Resources/transparent.gif" style="position:absolute; left:230px; top:631px; width:566px; height:179px"  >

<DIV id=u70 style="position:absolute; left:303px; top:677px; width:95px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u70_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Current Password</span></DIV></DIV>
<%= f.password_field :current_password, :id=>"71", :style=>"position:absolute; left:404px; top:672px; width:230px; height:25px; ; ; text-align: left ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none"   %>

<DIV id=u72 style="position:absolute; left:298px; top:721px; width:108px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u72_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">New Password</span></DIV></DIV>
<%= f.password_field :password, :id=>"73", :style=>"position:absolute; left:405px; top:717px; width:230px; height:25px; ; ; text-align: left ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none"   %>

<DIV id=u74 style="position:absolute; left:279px; top:762px; width:109px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u74_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Confirm Password</span></DIV></DIV>
<%= f.password_field :password_confirmation, :id=>"75", :style=>"position:absolute; left:406px; top:757px; width:230px; height:25px; ; ; text-align: left ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none"   %>

<div style="position:absolute; left:450px; top:930px; width:100px; height:25px; ; ; text-align: center ; font-family:'Arial'; font-size: 10pt; color:#000000; font-style:normal; font-weight:normal; text-decoration:none" ><div><%= f.submit "Modify" %></div></div>

<DIV id=u76ann style="font-size:1px; position:absolute; left:541px; top:926px; width:1px; height:1px; overflow:visible"></DIV>

<DIV id=u77 style="position:absolute; left:750px; top:930px; width:50px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u77_rtf><span style=" font-family:'Arial'; color:#0000FF; font-size:10pt;"><%= link_to "Cancel", :back %></span></DIV></DIV>
<DIV id=u77ann style="font-size:1px; position:absolute; left:791px; top:926px; width:1px; height:1px; overflow:visible"></DIV>

<% end %>

app/views/admin/home.html.erb
<html>
 <%= render :partial => "layouts/adminheader" %>




<IMG id=u65 src="Resources/transparent.gif" style="position:absolute; left:0px; top:669px; width:890px; height:75px"  >

<DIV id=u67 style="position:absolute; left:207px; top:694px; width:80px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u67_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Copyright ©</span></DIV></DIV>
<DIV id=u68 style="position:absolute; left:282px; top:694px; width:165px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u68_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">ProjectX.com 2007</span></DIV></DIV>
<span style="position:absolute; left:396px; top:693px; width:6px; height:23px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u69.png',sizingMethod='scale');
"><img style="width:6px; height:23px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u69.png" border="0" alt=""></span>

<IMG id=u69 src="Resources/transparent.gif" style="position:absolute; left:396px; top:693px; width:3px; height:20px">

<DIV id=u70 style="position:absolute; left:407px; top:694px; width:100px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u70_rtf><span style=" font-family:'Arial'; color:#4096EE; font-size:10pt;">Terms of use</span></DIV></DIV>
<DIV id=u71 style="position:absolute; left:506px; top:695px; width:100px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u71_rtf><span style=" font-family:'Arial'; color:#4096EE; font-size:10pt;">Privacy Policy</span></DIV></DIV>


<DIV id=u83 style="position:absolute; left:226px; top:218px; width:608px; height:32px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u83_rtf><span style=" font-family:'Arial'; color:#000000; font-size:10pt;">Welcome to admin page.&nbsp; Sample text which describes the details of the admin page will be displayed here.....</span></DIV></DIV>
<DIV id=u84 style="position:absolute; left:207px; top:148px; width:77px; height:22px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u84_rtf><span style=" font-family:'Arial'; color:#000000; font-size:14pt;"><b>Home</b></span></DIV></DIV>
<DIV id=ou85 style="position:absolute; left:5px; top:177px; width:175px; height:36px;; overflow:visible">

<span style="position:absolute; left:-3px; top:-3px; width:183px; height:44px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u85.png',sizingMethod='scale');
"><img style="width:183px; height:44px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u85.png" border="0" alt=""></span>

</DIV>
<DIV id=u85container style="position:absolute; left:5px; top:177px; width:175px; height:36px;; overflow:visible">

<DIV id=u86 style="position:absolute; left:2px; top:9.5px; width:170px; height:16px; ; ; text-align: center ; font-family:Arial; text-align:left;" >
<DIV id=u86_rtf>&nbsp;</DIV></DIV>
</DIV>
<IMG id=u85 src="Resources/transparent.gif" style="position:absolute; left:5px; top:177px; width:174px; height:35px"  >

<DIV id=u87 style="position:absolute; left:18px; top:185px; width:102px; height:18px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u87_rtf><span style=" font-family:'Verdana'; color:#FFFFFF; font-size:11pt;"><b>Template</b></span></DIV></DIV>
<DIV id=ou88 style="position:absolute; left:5px; top:213px; width:175px; height:178px;; overflow:visible">

<span style="position:absolute; left:-3px; top:-3px; width:183px; height:186px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u88.png',sizingMethod='scale');
"><img style="width:183px; height:186px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u88.png" border="0" alt=""></span>

</DIV>
<DIV id=u88container style="position:absolute; left:5px; top:213px; width:175px; height:178px;; overflow:visible">

<DIV id=u89 style="position:absolute; left:2px; top:80.5px; width:170px; height:16px; ; ; text-align: center ; font-family:Arial; text-align:left;" >
<DIV id=u89_rtf>&nbsp;</DIV></DIV>
</DIV>
<IMG id=u88 src="Resources/transparent.gif" style="position:absolute; left:5px; top:213px; width:174px; height:177px"  >

<DIV id=u90 style="position:absolute; left:31px; top:225px; width:80px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u90_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Dashboard', admin_home_path %></span></DIV></DIV>
<span style="position:absolute; left:7px; top:246px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u91.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u91.png" border="0" alt=""></span>

<IMG id=u91 src="Resources/transparent.gif" style="position:absolute; left:7px; top:245.5px; width:170px; height:2px">

<DIV id=u92 style="position:absolute; left:31px; top:256px; width:90px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u92_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'My Account', edit_admin_registration_path %></span></DIV></DIV>
<DIV id=u92ann style="font-size:1px; position:absolute; left:112px; top:252px; width:1px; height:1px; overflow:visible"></DIV>

<span style="position:absolute; left:7px; top:282px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u93.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u93.png" border="0" alt=""></span>

<IMG id=u93 src="Resources/transparent.gif" style="position:absolute; left:7px; top:281.5px; width:170px; height:2px">

<DIV id=u94 style="position:absolute; left:33px; top:292px; width:77px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u94_rtf><span style=" font-family:'Arial'; color:#333399; font-size:10pt;">Insert Staff</span></DIV></DIV>
<DIV id=u94ann style="font-size:1px; position:absolute; left:101px; top:288px; width:1px; height:1px; overflow:visible"></DIV>


<DIV id=u96 style="position:absolute; left:33px; top:326px; width:70px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u96_rtf><span style=" font-family:'Arial'; color:#333399; font-size:10pt;"><%= link_to 'Insert FAQ', new_faq_path %></span></DIV></DIV>
<DIV id=u96ann style="font-size:1px; position:absolute; left:94px; top:322px; width:1px; height:1px; overflow:visible"></DIV>

<span style="position:absolute; left:7px; top:315px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u97.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u97.png" border="0" alt=""></span>

<IMG id=u97 src="Resources/transparent.gif" style="position:absolute; left:7px; top:314.5px; width:170px; height:2px">

<span style="position:absolute; left:7px; top:349px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/adminpage_files/u98.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/adminpage_files/u98.png" border="0" alt=""></span>

<IMG id=u98 src="Resources/transparent.gif" style="position:absolute; left:7px; top:348.5px; width:170px; height:2px">
<SCRIPT src="Resources/axurerp_pagescript.js"></SCRIPT>