config/routes.rb
Sample::Application.routes.draw do

  get "adminclosedtickets/show"

 match "adminclosedtickets/view/:id"  => "adminclosedtickets#view"

  match "adminclosedtickets/assign/:id" => "adminclosedtickets#assign"

match "adminclosedtickets/support/:id" => "adminclosedtickets#support"

  match "contacts/accinfo" => "contacts#accinfo"
  match "home/contactus/:id" => "home#contactus"
  match "contacts/contact" => "contacts#contact"
 match "contacts/contact_update" => "contacts#contact_update"
 match "contacts/acc_update" => "contacts#acc_update"

  devise_for :admins
  devise_for :users
  resources :categories
  resources :news
  resources :depts
  resources :faqs

  resources :tickets do
  resources :posts
  end
  resources :contacts
  match 'home/search' => 'home#search'
  get "admin/createstaff"
  get "home/news"
  get "admin/createstaff"
  get "admin/staffhome"
  get "knowlwedgebase/kbase"
  get "admin/home"
  get "admin/ticket"
  get "home/login"
  get "home/contactus"
  get "opentickets/assignticket"
  get "home/homepage"
  get "adminopentickets/staff"
  get "knowlwedgebase/detail"
  get "staff/ticket"
  get "staff/time"
  get "category/create"
  get "category/update"
  get "category/destroy"
  get "posts/create"
  get "adminopentickets/show"
  get "adminopentickets/assign"
  get "adminopentickets/support"
  get "adminpendingtickets/show"
  match 'tickets/show/:id' => 'tickets#show'
  match 'home/newsview/:id' => 'home#newsview'
  match "knowlwedgebase/show/:id" => "knowlwedgebase#show"
  match "knowlwedgebase/detail/:id" => "knowlwedgebase#detail"
  match "knowlwedgebase/kbase/:id" => "knowlwedgebase#kbase"
  match 'adminpendingtickets/view/:id' => 'adminpendingtickets#view'
  match 'adminpendingtickets/assign/:id' => 'adminpendingtickets#assign'

  match 'adminpendingtickets/change/:id' => 'adminpendingtickets#change'
  match 'adminpendingtickets/support/:id' => 'adminpendingtickets#support'
  match 'adminopentickets/view/:id' => 'adminopentickets#view'
  match 'adminopentickets/assign/:id' => 'adminopentickets#assign'
  match 'adminopentickets/support/:id' => 'adminopentickets#support'
  
   
  
 

    root :to => "home#homepage"
    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
has_many :tickets
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :username, :phone, :mobile, :department, :ticket_notifier, :privilege, :find_your_attachment

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :faqs
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/dept.rb
class Dept < ActiveRecord::Base
	has_many :tickets
end

app/models/faq.rb
class Faq < ActiveRecord::Base
belongs_to :categories	
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :ticket
end

app/models/posts.rb
class Posts < ActiveRecord::Base
belongs_to:tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
has_many :posts
belongs_to :admin
has_one :dept
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
attr_accessible :to, :category, :priority, :subject, :message, :created_at, :updated_at, :status, :customer_name, :user_id, :staff_id, :avatar_file_name, :avatar_file_size, :avatar_file_type, :avatar_file_updatedat,:staff_email, :client_email
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :fullname, :company, :address1, :address2, :city, :state, :country, :phone1, :phone2, :fax, :web, :username, :admin_id
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
before_filter :authenticate_admin!
  def index
    @depts = Dept.all

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @depts }
    end
  end

  def show
    @dept = Dept.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @dept }
    end
  end

  def new
    @dept = Dept.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @dept }
    end
  end


  def edit
    @dept = Dept.find(params[:id])
  end

  def create
    @dept = Dept.new(params[:dept])

    respond_to do |format|
      if @dept.save
        format.html { redirect_to(@dept, :notice => 'Dept was successfully created.') }
        format.xml  { render :xml => @dept, :status => :created, :location => @dept }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dept.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @dept = Dept.find(params[:id])

    respond_to do |format|
      if @dept.update_attributes(params[:dept])
        format.html { redirect_to(@dept, :notice => 'Dept was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dept.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @dept = Dept.find(params[:id])
    @dept.destroy

    respond_to do |format|
      format.html { redirect_to(depts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/depts/_form.html.erb
	
<DIV id=u6 style="position:absolute; left:20px; top:300px; width:130px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u6_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Manage Department', depts_path %></span></DIV></DIV>
<DIV id=u7 style="position:absolute; left:20px; top:264px; width:120px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u7_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Insert Department',new_dept_path %></span></DIV></DIV>
<DIV id=u7ann style="font-size:1px; position:absolute; left:131px; top:260px; width:1px; height:1px; overflow:visible"></DIV>

<span style="position:absolute; left:10px; top:253px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='Admin -- List View of Department_files/u8.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="Admin -- List View of Department_files/u8.png" border="0" alt=""></span>

<IMG id=u8 src="Resources/transparent.gif" style="position:absolute; left:10px; top:252.5px; width:170px; height:2px">

<DIV id=u9 style="position:absolute; left:20px; top:229px; width:140px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u9_rtf><span style=" color:#333399; font-size:10pt;">Dashboard</span></DIV></DIV>
<DIV id=u52container style="position:absolute; left:200px; top:181px; width:575px; height:36px;; overflow:visible">

<script src="/javascripts/livevalidation_standalone.js"></script>
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_name %><br />
    <%= f.text_field :department_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

 <script>
var f1 = new LiveValidation('dept_department_name');
f1.add( Validate.Presence ); </script>

 <script>
var f2 = new LiveValidation('dept_description');
f2.add( Validate.Presence ); </script>

 <script>
var f3 = new LiveValidation('dept_email');
f3.add( Validate.Presence ); </script>

<% end %>
</DIV>

app/views/depts/edit.html.erb
<%= render 'form' %>


<%= link_to 'Cancel', depts_path %>

app/views/depts/index.html.erb
<DIV id=u6 style="position:absolute; left:20px; top:300px; width:130px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u6_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Manage Department', depts_path %></span></DIV></DIV>
<DIV id=u7 style="position:absolute; left:20px; top:264px; width:120px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u7_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Insert Department',new_dept_path %></span></DIV></DIV>
<DIV id=u7ann style="font-size:1px; position:absolute; left:131px; top:260px; width:1px; height:1px; overflow:visible"></DIV>

<span style="position:absolute; left:10px; top:253px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='Admin -- List View of Department_files/u8.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="Admin -- List View of Department_files/u8.png" border="0" alt=""></span>

<IMG id=u8 src="Resources/transparent.gif" style="position:absolute; left:10px; top:252.5px; width:170px; height:2px">

<DIV id=u9 style="position:absolute; left:20px; top:229px; width:140px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u9_rtf><span style=" color:#333399; font-size:10pt;">Dashboard</span></DIV></DIV>

<DIV id=u52container style="position:absolute; left:200px; top:181px; width:175px; height:36px;; overflow:visible">


<h1>Listing depts</h1>

<table cellspacing = 30>
  <tr>
    <th>Department name</th>
    
    <th>Email</th>
    <th>Phone1</th>
    
    <th>Options</th>
    <th></th>
    <th></th>
  </tr>

<% @depts.each do |dept| %>
  <tr>
    <td><%= link_to dept.department_name, dept_path(dept) %></td>
    
    <td><%= dept.email %></td>
    <td><%= dept.phone1 %></td>
    
    
    
    <td><%= link_to 'Edit', edit_dept_path(dept) %></td>
    <td><%= link_to 'Delete', dept, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

</DIV>

app/views/depts/new.html.erb
<%= render 'form' %>

<%= link_to 'Cancel', depts_path %>

app/views/depts/show.html.erb
<DIV id=u6 style="position:absolute; left:20px; top:300px; width:130px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u6_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Manage Department', depts_path %></span></DIV></DIV>
<DIV id=u7 style="position:absolute; left:20px; top:264px; width:120px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u7_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Insert Department',new_dept_path %></span></DIV></DIV>
<DIV id=u7ann style="font-size:1px; position:absolute; left:131px; top:260px; width:1px; height:1px; overflow:visible"></DIV>

<span style="position:absolute; left:10px; top:253px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='Admin -- List View of Department_files/u8.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="Admin -- List View of Department_files/u8.png" border="0" alt=""></span>

<IMG id=u8 src="Resources/transparent.gif" style="position:absolute; left:10px; top:252.5px; width:170px; height:2px">

<DIV id=u9 style="position:absolute; left:20px; top:229px; width:140px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u9_rtf><span style=" color:#333399; font-size:10pt;">Dashboard</span></DIV></DIV>

<DIV id=u52container style="position:absolute; left:200px; top:181px; width:175px; height:36px;; overflow:visible">

<p id="notice"><%= notice %></p>

<p>
  <b>Department name:</b>
  <%= @dept.department_name %>
</p>

<p>
  <b>Description:</b>
  <%= @dept.description %>
</p>

<p>
  <b>Email:</b>
  <%= @dept.email %>
</p>

<p>
  <b>Phone1:</b>
  <%= @dept.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @dept.phone2 %>
</p>

<p>
  <b>Fax:</b>
  <%= @dept.fax %>
</p>


<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Cancel', depts_path %>
</DIV>