config/routes.rb
Sample::Application.routes.draw do

  get "adminclosedtickets/show"

 match "adminclosedtickets/view/:id"  => "adminclosedtickets#view"

  match "adminclosedtickets/assign/:id" => "adminclosedtickets#assign"

match "adminclosedtickets/support/:id" => "adminclosedtickets#support"

  match "contacts/accinfo" => "contacts#accinfo"
  match "home/contactus/:id" => "home#contactus"
  match "contacts/contact" => "contacts#contact"
 match "contacts/contact_update" => "contacts#contact_update"
 match "contacts/acc_update" => "contacts#acc_update"

  devise_for :admins
  devise_for :users
  resources :categories
  resources :news
  resources :depts
  resources :faqs

  resources :tickets do
  resources :posts
  end
  resources :contacts
  match 'home/search' => 'home#search'
  get "admin/createstaff"
  get "home/news"
  get "admin/createstaff"
  get "admin/staffhome"
  get "knowlwedgebase/kbase"
  get "admin/home"
  get "admin/ticket"
  get "home/login"
  get "home/contactus"
  get "opentickets/assignticket"
  get "home/homepage"
  get "adminopentickets/staff"
  get "knowlwedgebase/detail"
  get "staff/ticket"
  get "staff/time"
  get "category/create"
  get "category/update"
  get "category/destroy"
  get "posts/create"
  get "adminopentickets/show"
  get "adminopentickets/assign"
  get "adminopentickets/support"
  get "adminpendingtickets/show"
  match 'tickets/show/:id' => 'tickets#show'
  match 'home/newsview/:id' => 'home#newsview'
  match "knowlwedgebase/show/:id" => "knowlwedgebase#show"
  match "knowlwedgebase/detail/:id" => "knowlwedgebase#detail"
  match "knowlwedgebase/kbase/:id" => "knowlwedgebase#kbase"
  match 'adminpendingtickets/view/:id' => 'adminpendingtickets#view'
  match 'adminpendingtickets/assign/:id' => 'adminpendingtickets#assign'

  match 'adminpendingtickets/change/:id' => 'adminpendingtickets#change'
  match 'adminpendingtickets/support/:id' => 'adminpendingtickets#support'
  match 'adminopentickets/view/:id' => 'adminopentickets#view'
  match 'adminopentickets/assign/:id' => 'adminopentickets#assign'
  match 'adminopentickets/support/:id' => 'adminopentickets#support'
  
   
  
 

    root :to => "home#homepage"
    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
has_many :tickets
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :username, :phone, :mobile, :department, :ticket_notifier, :privilege, :find_your_attachment

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :faqs
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/dept.rb
class Dept < ActiveRecord::Base
	has_many :tickets
end

app/models/faq.rb
class Faq < ActiveRecord::Base
belongs_to :categories	
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :ticket
end

app/models/posts.rb
class Posts < ActiveRecord::Base
belongs_to:tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
has_many :posts
belongs_to :admin
has_one :dept
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
attr_accessible :to, :category, :priority, :subject, :message, :created_at, :updated_at, :status, :customer_name, :user_id, :staff_id, :avatar_file_name, :avatar_file_size, :avatar_file_type, :avatar_file_updatedat,:staff_email, :client_email
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :fullname, :company, :address1, :address2, :city, :state, :country, :phone1, :phone2, :fax, :web, :username, :admin_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_filter :authenticate_admin!
	
  def index
    @categories = Category.all

    respond_to do |format|
      format.html
      format.xml  { render :xml => @categories }
    end
  end

  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @category }
    end
  end

  def new
    @category = Category.new

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category) }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/categories/_form.html.erb
<script src="/javascripts/livevalidation_standalone.js"></script>
<DIV id=u54 style="position:absolute; left:21px; top:189px; width:109px; height:18px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u54_rtf><span style=" font-family:'Verdana'; color:#FFFFFF; font-size:11pt;"><b>Template</b></span></DIV></DIV>
<DIV id=ou55 style="position:absolute; left:8px; top:217px; width:175px; height:194px;; overflow:visible">

<span style="position:absolute; left:-3px; top:-3px; width:183px; height:202px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u55.png',sizingMethod='scale');
"><img style="width:183px; height:202px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u55.png" border="0" alt=""></span>

</DIV>
<DIV id=u55container style="position:absolute; left:8px; top:217px; width:175px; height:194px;; overflow:visible">

<DIV id=u56 style="position:absolute; left:2px; top:88.5px; width:170px; height:16px; ; ; text-align: center ; font-family:Arial; text-align:left;" >
<DIV id=u56_rtf>&nbsp;</DIV></DIV>
</DIV>
<IMG id=u55 src="Resources/transparent.gif" style="position:absolute; left:8px; top:217px; width:174px; height:193px"  >

<span style="position:absolute; left:10px; top:289px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u57.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u57.png" border="0" alt=""></span>

<IMG id=u57 src="Resources/transparent.gif" style="position:absolute; left:10px; top:288.5px; width:170px; height:2px">

<DIV id=u58 style="position:absolute; left:20px; top:265px; width:130px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u58_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'View / Modify FAQs', faqs_path %></span></DIV></DIV>
<DIV id=u59 style="position:absolute; left:21px; top:304px; width:80px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u59_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Insert FAQ', new_faq_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:253px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u60.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u60.png" border="0" alt=""></span>

<IMG id=u60 src="Resources/transparent.gif" style="position:absolute; left:10px; top:252.5px; width:170px; height:2px">

<DIV id=u61 style="position:absolute; left:22px; top:228px; width:140px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u61_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Knowledge base', categories_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:334px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u62.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u62.png" border="0" alt=""></span>

<IMG id=u62 src="Resources/transparent.gif" style="position:absolute; left:10px; top:333.5px; width:170px; height:2px">

<DIV id=u63 style="position:absolute; left:19px; top:343px; width:100px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u63_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Create Category', new_category_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:367px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u64.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u64.png" border="0" alt=""></span>

<IMG id=u64 src="Resources/transparent.gif" style="position:absolute; left:10px; top:366.5px; width:170px; height:2px">

<DIV id=u65 style="position:absolute; left:20px; top:380px; width:120px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u65_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Manage Category', categories_path %></span></DIV></DIV>
<DIV id=ou66 style="position:absolute; left:209px; top:188px; width:613px; height:483px;; overflow:visible"></DIV>
<DIV style="position:absolute; left:200px; top:200px;width:613px; height:483px; overflow:visible">

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category_name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :description, :size=>"45x5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<script>
var f1 = new LiveValidation('category_category');
f1.add( Validate.Presence ); </script>
<script>
var f2 = new LiveValidation('category_description');
f2.add( Validate.Presence ); </script>
<% end %>
</DIV>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<DIV id=u54 style="position:absolute; left:21px; top:189px; width:109px; height:18px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u54_rtf><span style=" font-family:'Verdana'; color:#FFFFFF; font-size:11pt;"><b>Template</b></span></DIV></DIV>
<DIV id=ou55 style="position:absolute; left:8px; top:217px; width:175px; height:194px;; overflow:visible">

<span style="position:absolute; left:-3px; top:-3px; width:183px; height:202px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u55.png',sizingMethod='scale');
"><img style="width:183px; height:202px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u55.png" border="0" alt=""></span>

</DIV>
<DIV id=u55container style="position:absolute; left:8px; top:217px; width:175px; height:194px;; overflow:visible">

<DIV id=u56 style="position:absolute; left:2px; top:88.5px; width:170px; height:16px; ; ; text-align: center ; font-family:Arial; text-align:left;" >
<DIV id=u56_rtf>&nbsp;</DIV></DIV>
</DIV>
<IMG id=u55 src="Resources/transparent.gif" style="position:absolute; left:8px; top:217px; width:174px; height:193px"  >

<span style="position:absolute; left:10px; top:289px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u57.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u57.png" border="0" alt=""></span>

<IMG id=u57 src="Resources/transparent.gif" style="position:absolute; left:10px; top:288.5px; width:170px; height:2px">

<DIV id=u58 style="position:absolute; left:20px; top:265px; width:130px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u58_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'View / Modify FAQs', faqs_path %></span></DIV></DIV>
<DIV id=u59 style="position:absolute; left:21px; top:304px; width:80px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u59_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Insert FAQ', new_faq_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:253px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u60.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u60.png" border="0" alt=""></span>

<IMG id=u60 src="Resources/transparent.gif" style="position:absolute; left:10px; top:252.5px; width:170px; height:2px">

<DIV id=u61 style="position:absolute; left:22px; top:228px; width:140px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u61_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Knowledge base', categories_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:334px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u62.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u62.png" border="0" alt=""></span>

<IMG id=u62 src="Resources/transparent.gif" style="position:absolute; left:10px; top:333.5px; width:170px; height:2px">

<DIV id=u63 style="position:absolute; left:19px; top:343px; width:100px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u63_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Create Category', new_category_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:367px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u64.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u64.png" border="0" alt=""></span>

<IMG id=u64 src="Resources/transparent.gif" style="position:absolute; left:10px; top:366.5px; width:170px; height:2px">

<DIV id=u65 style="position:absolute; left:20px; top:380px; width:120px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u65_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Manage Category', categories_path %></span></DIV></DIV>
<DIV id=ou66 style="position:absolute; left:209px; top:188px; width:613px; height:483px;; overflow:visible">
<h1>Listing categories</h1>

<table border = "1">
  <tr>
    <th>Category name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.category_name, category %></td>
    <td><%= category.description %></td>
    
    
    <td><%= link_to 'Delete', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>
</DIV>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<DIV id=u54 style="position:absolute; left:21px; top:189px; width:109px; height:18px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u54_rtf><span style=" font-family:'Verdana'; color:#FFFFFF; font-size:11pt;"><b>Template</b></span></DIV></DIV>
<DIV id=ou55 style="position:absolute; left:8px; top:217px; width:175px; height:194px;; overflow:visible">

<span style="position:absolute; left:-3px; top:-3px; width:183px; height:202px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u55.png',sizingMethod='scale');
"><img style="width:183px; height:202px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u55.png" border="0" alt=""></span>

</DIV>
<DIV id=u55container style="position:absolute; left:8px; top:217px; width:175px; height:194px;; overflow:visible">

<DIV id=u56 style="position:absolute; left:2px; top:88.5px; width:170px; height:16px; ; ; text-align: center ; font-family:Arial; text-align:left;" >
<DIV id=u56_rtf>&nbsp;</DIV></DIV>
</DIV>
<IMG id=u55 src="Resources/transparent.gif" style="position:absolute; left:8px; top:217px; width:174px; height:193px"  >

<span style="position:absolute; left:10px; top:289px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u57.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u57.png" border="0" alt=""></span>

<IMG id=u57 src="Resources/transparent.gif" style="position:absolute; left:10px; top:288.5px; width:170px; height:2px">

<DIV id=u58 style="position:absolute; left:20px; top:265px; width:130px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u58_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'View / Modify FAQs', faqs_path %></span></DIV></DIV>
<DIV id=u59 style="position:absolute; left:21px; top:304px; width:80px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u59_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Insert FAQ', new_faq_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:253px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u60.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u60.png" border="0" alt=""></span>

<IMG id=u60 src="Resources/transparent.gif" style="position:absolute; left:10px; top:252.5px; width:170px; height:2px">

<DIV id=u61 style="position:absolute; left:22px; top:228px; width:140px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u61_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Knowledge base', categories_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:334px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u62.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u62.png" border="0" alt=""></span>

<IMG id=u62 src="Resources/transparent.gif" style="position:absolute; left:10px; top:333.5px; width:170px; height:2px">

<DIV id=u63 style="position:absolute; left:19px; top:343px; width:100px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u63_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Create Category', new_category_path %></span></DIV></DIV>
<span style="position:absolute; left:10px; top:367px; width:173px; height:5px; ;
filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/images/Admin -- detail view of the FAQ_files/u64.png',sizingMethod='scale');
"><img style="width:173px; height:5px; filter:progid:DXImageTransform.Microsoft.Alpha(opacity=0);" 
src="/images/Admin -- detail view of the FAQ_files/u64.png" border="0" alt=""></span>

<IMG id=u64 src="Resources/transparent.gif" style="position:absolute; left:10px; top:366.5px; width:170px; height:2px">

<DIV id=u65 style="position:absolute; left:20px; top:380px; width:120px; height:16px; ; ; text-align: left ; font-family:Arial; text-align:left;" >
<DIV id=u65_rtf><span style=" color:#333399; font-size:10pt;"><%= link_to 'Manage Category', categories_path %></span></DIV></DIV>
<DIV id=ou66 style="position:absolute; left:209px; top:188px; width:613px; height:483px;; overflow:visible">


<p id="notice"><%= notice %></p>

<p>
  <b>Category name:</b>
  <%= @category.category_name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

</DIV>
</DIV>